### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by 02928shshwhwj** [SHRE-YANSH/SongBot#1]
There is a error when you try block any one
And error in chatlist.txt its embty

**Comment by SHRE-YANSH** [comment]
Fix your database then. The same code works for me.

**Comment by 02928shshwhwj** [comment]
The broblem in your code am pnly clicked on your buttom heroku and linked it with my bot

**Comment by SHRE-YANSH** [comment]
> The broblem in your code am pnly clicked on your buttom heroku and linked it with my bot

Please send me the logs in https://t.me/SongBotHelp
